import type { LensData } from "@/types/lens";

export const mockLensData: LensData[] = [
  {
    neighborhood_id: "tenderloin",
    neighborhood_name: "Tenderloin",
    raw_count: 8234,
    per_capita: 361.4,
    reference_raw: 1847,
    reference_per_capita: 617.6,
    low_confidence: false,
    per_capita_applicable: true,
    value: 155.3,
    reference_value: 36.0,
    clearance_rate: 6.1,
    reference_rate: 8.1,
    gap: -2.0,
    provisional: false,
  },
  {
    neighborhood_id: "outer-richmond",
    neighborhood_name: "Outer Richmond",
    raw_count: 1802,
    per_capita: 39.5,
    reference_raw: 1847,
    reference_per_capita: 617.6,
    low_confidence: false,
    per_capita_applicable: true,
    value: 7.2,
    reference_value: 36.0,
    clearance_rate: 10.3,
    reference_rate: 8.1,
    gap: 2.2,
    provisional: false,
  },
  {
    neighborhood_id: "golden-gate-park",
    neighborhood_name: "Golden Gate Park",
    raw_count: 1203,
    per_capita: null,
    reference_raw: 1847,
    reference_per_capita: 617.6,
    low_confidence: false,
    per_capita_applicable: false,
    value: null,
    reference_value: 36.0,
    clearance_rate: null,
    reference_rate: 8.1,
    gap: null,
    provisional: false,
  },
  {
    neighborhood_id: "presidio",
    neighborhood_name: "Presidio",
    raw_count: 94,
    per_capita: null,
    reference_raw: 1847,
    reference_per_capita: 617.6,
    low_confidence: true,
    per_capita_applicable: false,
    value: null,
    reference_value: 36.0,
    clearance_rate: null,
    reference_rate: 8.1,
    gap: null,
    provisional: false,
  },
];